# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Sandesh

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    commandOptions: '-backend-config=access_key=$(access-key) -lock=false'
    backendServiceArm: 'sandesh-test'
    backendAzureRmResourceGroupName: 'sandesh-group1'
    backendAzureRmStorageAccountName: 'sandeshblobstore'
    backendAzureRmContainerName: 'sandesh-test'
    backendAzureRmKey: 'test5.tfstate'
    
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    commandOptions: '-var kafka_api_key=$(kafka-api-key) -var kafka_api_secret=$(kafka-api-secret) -var confluent_cloud_api_key=$(confluent-cloud-api-key) -var confluent_cloud_api_secret=$(confluent-cloud-api-secret) -lock=false --out=tfplan'
    environmentServiceNameAzureRM: 'sandesh-test'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    commandOptions: '-var kafka_api_key=$(kafka-api-key) -var kafka_api_secret=$(kafka-api-secret) -var confluent_cloud_api_key=$(confluent-cloud-api-key) -var confluent_cloud_api_secret=$(confluent-cloud-api-secret) -lock=false'
    environmentServiceNameAzureRM: 'sandesh-test'
