project="projectA"
project_env="dev"
confluent_environment="env-xrz8qx"
confluent_kafka_cluster="lkc-okqdox"
confluent_schema_registry="lsrc-1w8n0v"
schema_registry_api_key="ITDSK3J7P2DA6X2B"
schema_registry_api_secret="ywO+nPL7z8g8vjaniUuEe8xCpUb4eNjDm2A5lDPx9lnwm3AL1/bwlK7SWuOAM1HX"
