# This is a basic workflow to help you get started with Actions

name: CI/CD with Terraform

on:
  push:
    branches: ["main"]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment:
      name: staging
    env:
      TF_VARS_FILE: qut.terraform.tfvars
      # Set an environment variable for the path to the credentials file
      GCP_CREDS_PATH: ${{ github.workspace }}/gcp_credentials.json

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: 'Create GCP Credentials File'
        id: 'gcp_credentials'
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > ${{ env.GCP_CREDS_PATH }}

      # Now, set the GOOGLE_APPLICATION_CREDENTIALS environment variable
      # for subsequent steps in the job.
      - name: 'Set GOOGLE_APPLICATION_CREDENTIALS'
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ env.GCP_CREDS_PATH }}" >> $GITHUB_ENV

      # Your Terraform steps will now automatically use the credentials
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ./terraform
      - name: Setup Terraform variables
        working-directory: ./terraform
        id: vars
        run: |
          cat > qut.terraform.tfvars <<EOF
          confluent_cloud_api_key = "${{ secrets.CONFLUENT_CLOUD_API_KEY }}"
          confluent_cloud_api_secret = "${{ secrets.CONFLUENT_CLOUD_API_SECRET }}"
          kafka_api_key = "${{ secrets.KAFKA_API_KEY }}"
          kafka_api_secret = "${{ secrets.KAFKA_API_SECRET }}"
          EOF
          cat qut.terraform.tfvars
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -var-file=qut.terraform.tfvars -out=PLAN
        working-directory: ./terraform
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./terraform/PLAN
          retention-days: 1

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
      name: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ./terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply PLAN
        working-directory: ./terraform
